from . import medical_patient
from . import medical_appointment
from . import medical_physician
from . import medical_pathology_category
from . import medical_pathology_group_member
from . import medical_pathology_group
from . import medical_pathology
from . import medical_patient_disease
from . import medical_patient_diseases 
from . import medical_patient_evaluation
from . import res_partner